# Generated by Django 2.1.1 on 2018-09-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('laptop', '0002_auto_20180908_1638'),
        ('resolution', '0001_initial'),
        ('displaySize', '0001_initial'),
        ('storage', '0001_initial'),
        ('laptopType', '0001_initial'),
        ('processorBrand', '0001_initial'),
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=200)),
                ('min_price', models.CharField(blank=True, max_length=50, null=True)),
                ('max_price', models.CharField(blank=True, max_length=50, null=True)),
                ('min_cores', models.CharField(blank=True, max_length=50, null=True)),
                ('max_cores', models.CharField(blank=True, max_length=50, null=True)),
                ('min_size', models.CharField(blank=True, max_length=4, null=True)),
                ('max_size', models.CharField(blank=True, max_length=4, null=True)),
                ('min_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('max_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('min_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('max_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='laptop.Laptop')),
                ('processor', models.ManyToManyField(blank=True, to='processorBrand.ProcessorBrand')),
                ('ram', models.ManyToManyField(blank=True, to='ram.Ram')),
                ('resolution', models.ManyToManyField(blank=True, to='resolution.Resolution')),
                ('size', models.ManyToManyField(blank=True, to='displaySize.DisplaySize')),
                ('storage', models.ManyToManyField(blank=True, to='storage.Storage')),
                ('type', models.ManyToManyField(blank=True, to='laptopType.LaptopType')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
