# Generated by Django 2.2.4 on 2019-09-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_productinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='description',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='status',
            field=models.CharField(choices=[('NOT_CONTACTED', 'Not Contacted'), ('ATTEMPTED_TO_CONTACT', 'Attempted to Contact'), ('ASKED_TO_CALL_LATER', 'Asked to Call Later'), ('DECISION_MAKING', 'Decision Making'), ('CLOSED_WON', 'Closed Won'), ('CLOSED LOST', 'Closed Lost')], default='NOT_CONTACTED', max_length=30),
        ),
    ]
