# Generated by Django 2.2.4 on 2019-09-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190925_0757'),
        ('inquiries', '0003_auto_20190928_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productinquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquired_product', to='products.Product'),
        ),
    ]
