# Generated by Django 2.2.4 on 2019-09-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190925_0757'),
        ('inquiries', '0004_auto_20190928_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='max_cores',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='max_ram',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='max_storage',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='min_cores',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='min_ram',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='min_size',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='min_storage',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='size',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='type',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='description',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_laptop', to='products.Product'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NOT_CONTACTED', 'Not Contacted'), ('ATTEMPTED_TO_CONTACT', 'Attempted to Contact'), ('ASKED_TO_CALL_LATER', 'Asked to Call Later'), ('DECISION_MAKING', 'Decision Making'), ('CLOSED_WON', 'Closed Won'), ('CLOSED LOST', 'Closed Lost')], default='NOT_CONTACTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquired_laptop', to='laptop.Laptop'),
        ),
    ]
