# Generated by Django 2.2.4 on 2019-09-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_auto_20190928_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_laptop', to='laptop.Laptop'),
        ),
    ]
