# Generated by Django 2.2.4 on 2019-11-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_auto_20190928_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='source',
        ),
    ]
