# Generated by Django 2.2.4 on 2019-11-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_remove_inquiry_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='sold',
        ),
    ]
