# Generated by Django 2.1.1 on 2019-04-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perks',
            options={'ordering': ['name'], 'verbose_name': 'Perks', 'verbose_name_plural': 'Perks'},
        ),
    ]
