# Generated by Django 2.1.1 on 2018-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('processorBrand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: i7-7700HQ', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('min_frequency', models.FloatField(help_text='В ГГц. К примеру: 2.8')),
                ('max_frequency', models.FloatField(help_text='В ГГЦ. К примеру: 3.8')),
                ('cores', models.IntegerField(help_text='В шт. К примеру: 4')),
                ('threads', models.IntegerField(help_text='В шт. К примеру: 8')),
                ('cache', models.FloatField(help_text='В мегабайтах. К примеру: 6')),
                (
                    'integrated_graphics',
                    models.CharField(help_text='К примеру: Intel® HD Graphics 630', max_length=255)),
                ('brand',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processorBrand.ProcessorBrand')),
            ],
        ),
    ]
