# Generated by Django 2.1.1 on 2018-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='integrated_graphics',
            field=models.CharField(blank=True, help_text='К примеру: Intel® HD Graphics 630', max_length=255, null=True),
        ),
    ]
