# Generated by Django 2.1 on 2018-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20180913_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['name']},
        ),
    ]
