# Generated by Django 2.1 on 2018-10-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20180922_1652'),
        ('processor', '0003_auto_20181007_1305'),
    ]

    operations = [
    ]
