# Generated by Django 2.2.4 on 2019-11-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_merge_20181011_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['-name']},
        ),
    ]
