# Generated by Django 2.2.4 on 2019-11-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_auto_20191105_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['name']},
        ),
    ]
