# Generated by Django 2.1.1 on 2018-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Asus, Acer, HP и т.д.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
