# Generated by Django 2.1.1 on 2018-10-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20181007_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
