# Generated by Django 2.2.4 on 2019-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20181008_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
