# Generated by Django 2.1.1 on 2018-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCardBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: nVidia', max_length=250)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Graphics Card Brand',
                'verbose_name_plural': 'Graphics Card Brands',
            },
        ),
    ]
