# Generated by Django 2.2.4 on 2020-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200116_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
