# Generated by Django 2.2.4 on 2019-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190929_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.AddField(
            model_name='laptop',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testing/thumbs'),
        ),
    ]
