# Generated by Django 2.1.2 on 2018-11-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181031_0406'),
        ('accounts', '0006_auto_20181108_1117'),
    ]

    operations = [
    ]
