# Generated by Django 2.2.4 on 2020-01-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopperks',
            options={'ordering': ['name'], 'verbose_name': 'Laptop Perks', 'verbose_name_plural': 'Laptop Perks'},
        ),
    ]
