# Generated by Django 2.2.4 on 2020-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfig', '0002_auto_20200129_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInOneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Во множественном числе. К примеру: Бизнес Моноблоки', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('name_singular', models.CharField(help_text='В единственном числе. К примеру: Бизнес Моноблок', max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(default='default.png', upload_to='aio-types')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerPerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Сенсорный экран', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Laptop Perks',
                'verbose_name_plural': 'Laptop Perks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesktopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Во множественном числе. К примеру: Игровые Компьютеры, Рабочие Станции и т.д', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('name_singular', models.CharField(help_text='В единственном числе. К примеру: Игровой Компьютер', max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(default='default.png', upload_to='aio-types')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Черно-белый или Цветной', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: A4, A3 или А1', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Принтер, Сканер, Ксерокс и т.д.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterPerks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wi-Fi, Автоподача', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterTechnologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Лазерный или Струйный', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LaptopPerks',
        ),
        migrations.AlterModelOptions(
            name='laptoptype',
            options={},
        ),
        migrations.AlterField(
            model_name='laptoptype',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
