# Generated by Django 2.2.4 on 2020-02-07 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productconfig', '0003_auto_20200206_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Во множественном числе. К примеру: УльтрабукИ, трансформеры и т.д.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('name_singular', models.CharField(help_text='В единственном числе. К примеру: Ультрабук, трансформер и т.д.', max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(default='default.png', upload_to='laptop-types')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Черно-белый или Цветной', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='name_singular',
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='allinonetype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='name_singular',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='desktoptype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='name_singular',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='laptoptype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printercolortype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printercolortype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='printercolortype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printerformat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printerformat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='printerformat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printerfunction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printerfunction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='printerfunction',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printerperks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printerperks',
            name='name',
        ),
        migrations.RemoveField(
            model_name='printerperks',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printertechnologytype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printertechnologytype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='printertechnologytype',
            name='slug',
        ),
        migrations.AddField(
            model_name='allinonetype',
            name='computertype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.ComputerType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desktoptype',
            name='computertype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.ComputerType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptoptype',
            name='computertype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.ComputerType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printercolortype',
            name='printerconfig_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.PrinterConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerformat',
            name='printerconfig_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.PrinterConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerfunction',
            name='printerconfig_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.PrinterConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerperks',
            name='printerconfig_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.PrinterConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printertechnologytype',
            name='printerconfig_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productconfig.PrinterConfig'),
            preserve_default=False,
        ),
    ]
