# Generated by Django 2.1.4 on 2018-12-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        ('laptop', '0006_auto_20181013_1235'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('laptop', 'warehouse')},
        ),
    ]
