# Generated by Django 2.2.4 on 2019-11-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0005_brand_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='images/products/categories')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(help_text='Отсканируйте баркод', max_length=12)),
                ('name', models.CharField(help_text='К примеру: XPS 13', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, help_text='К примеру: 81XVS440S', max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_price', models.IntegerField(default=0, help_text='Старая цена. Оставьте 0 если не идет акция')),
                ('price', models.IntegerField(help_text='Введите сумму в USD')),
                ('viewed', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/products/thumbnails')),
                ('awaiting', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_brand', to='brand.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'ordering': ['-created'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
