# Generated by Django 2.2.4 on 2020-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200126_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='optane',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
