# Generated by Django 2.2.4 on 2020-01-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200126_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=12, help_text='Введите срок гарантии в месяцах'),
        ),
    ]
