# Generated by Django 2.2.4 on 2020-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='short_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
