# Generated by Django 2.2.4 on 2020-02-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200129_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/products/thumbnails'),
            preserve_default=False,
        ),
    ]
