# Generated by Django 2.2.4 on 2020-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfig', '0003_auto_20200206_1541'),
        ('shop', '0015_auto_20200206_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='allinone',
            name='perks',
            field=models.ManyToManyField(to='productconfig.ComputerPerk'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='perks',
            field=models.ManyToManyField(to='productconfig.ComputerPerk'),
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
