# Generated by Django 2.2.4 on 2020-02-06 14:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('productconfig', '0003_auto_20200206_1541'),
        ('shop', '0016_auto_20200206_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('speed', models.PositiveIntegerField(help_text='скорость печати за 1 минуту')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productconfig.PrinterColorType')),
                ('formats', models.ManyToManyField(to='productconfig.PrinterFormat')),
                ('functions', models.ManyToManyField(to='productconfig.PrinterFunction')),
                ('perks', models.ManyToManyField(to='productconfig.PrinterPerks')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productconfig.PrinterTechnologyType')),
            ],
            bases=('shop.product',),
        ),
    ]
