# Generated by Django 2.2.4 on 2020-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_printer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allinone',
            old_name='desktop_type',
            new_name='all_in_one_type',
        ),
    ]
