# Generated by Django 2.1.1 on 2018-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное имя покупателя. Например: Кобулов Икбол', max_length=255)),
                ('phone',
                 models.CharField(help_text='Номер телефона покупателя в формате 998 91 192 2228', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('laptop',
                 models.ForeignKey(blank=True, help_text='Какой ноутбук купили? Выберите из списка', null=True,
                                   on_delete=django.db.models.deletion.CASCADE, to='laptop.Laptop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
