# Generated by Django 2.1.4 on 2018-12-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_laptop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'phone')},
        ),
    ]
