# Generated by Django 2.1.4 on 2018-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
