# Generated by Django 2.1.4 on 2018-12-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_interested_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interested_in',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='laptop.Laptop'),
        ),
    ]
