# Generated by Django 2.1.4 on 2018-12-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20181211_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='interested_in',
        ),
    ]
