# Generated by Django 2.1.4 on 2018-12-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_lead_interested_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
