# Generated by Django 2.1.1 on 2018-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('graphicsCardBrand', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: GeForce GTX', max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('memory_interface', models.CharField(help_text='К примеру: GDDR5', max_length=20)),
                ('memory_interface_width', models.IntegerField(help_text='В битах. К примеру: 128')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='graphicsCardBrand.GraphicsCardBrand')),
            ],
            options={
                'verbose_name': 'Graphics Card',
                'verbose_name_plural': 'Graphics Cards',
            },
        ),
    ]
