# Generated by Django 2.1.4 on 2018-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicsCardBrand', '0001_initial'),
        ('graphicsCard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphicscard',
            options={'ordering': ['name'], 'verbose_name': 'Graphics Card', 'verbose_name_plural': 'Graphics Cards'},
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='name',
            field=models.CharField(help_text='К примеру: GeForce GTX 1060', max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='graphicscard',
            unique_together={('name', 'brand')},
        ),
    ]
