# Generated by Django 2.1.1 on 2018-09-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_warehouse',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse',
                                   to='warehouses.Warehouse')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.Laptop')),
                ('moved_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_warehouse',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse',
                                   to='warehouses.Warehouse')),
            ],
            options={
                'verbose_name': ('Stock Movement',),
                'verbose_name_plural': 'Stock Movements',
            },
        ),
    ]
