# Generated by Django 2.1.1 on 2018-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('graphicsCard', '0001_initial'),
        ('storage', '0001_initial'),
        ('ram', '0001_initial'),
        ('audio', '0001_initial'),
        ('perks', '0001_initial'),
        ('resolution', '__first__'),
        ('processor', '0001_initial'),
        ('displaySize', '__first__'),
        ('brand', '0001_initial'),
        ('laptopType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/laptop_images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: XPS 13', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('model', models.CharField(blank=True, help_text='К примеру: 1470 80XA', max_length=255, null=True)),
                ('ram', models.IntegerField()),
                ('main_storage', models.IntegerField()),
                ('secondary_storage', models.IntegerField(blank=True, null=True)),
                ('graphics_card_memory',
                 models.IntegerField(blank=True, help_text='В ГГБ. К примеру 2 или 4', null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Введите стартовое количество')),
                ('price', models.IntegerField(help_text='Введите сумму в USD')),
                ('viewed', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Audio')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand',
                                            to='brand.Brand')),
                ('graphics_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    to='graphicsCard.GraphicsCard')),
                ('laptop_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopType.LaptopType')),
                ('main_storage_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_storage',
                                   to='storage.Storage')),
                ('perks', models.ManyToManyField(blank=True, help_text='Выберите все нужные опции нажатием кнопки CTRL',
                                                 to='perks.Perks')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Processor')),
                ('ram_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_type', to='ram.Ram')),
                ('resolution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolution.Resolution')),
                ('screen_size',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaySize.DisplaySize')),
                ('secondary_storage_type',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='secondary_storage', to='storage.Storage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='images', to='laptop.Laptop'),
        ),
    ]
