# Generated by Django 2.1.1 on 2018-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20180908_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='viewed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
