# Generated by Django 2.1 on 2018-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_auto_20180911_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-created']},
        ),
    ]
