# Generated by Django 2.1.4 on 2018-12-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0006_auto_20181013_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='old_price',
            field=models.IntegerField(default=0, help_text='Старая цена. Оставьте 0 если не идет акция'),
        ),
    ]
