# Generated by Django 2.1.1 on 2019-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0007_laptop_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_thumbnails'),
        ),
    ]
