# Generated by Django 2.1.1 on 2019-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0009_laptop_awaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='vat',
            field=models.BooleanField(default=False),
        ),
    ]
