# Generated by Django 2.2.4 on 2019-09-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0010_laptop_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='upc',
            field=models.CharField(default=1, help_text='Отсканируйте баркод', max_length=12),
            preserve_default=False,
        ),
    ]