# Generated by Django 2.2.4 on 2019-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0011_laptop_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='black_friday',
            field=models.BooleanField(default=False),
        ),
    ]
