# Generated by Django 2.2.4 on 2020-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.TextField(default='Empty'),
        ),
    ]
