# Generated by Django 2.2.4 on 2020-02-03 20:58

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200204_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
