# Generated by Django 2.2.4 on 2020-02-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200203_1729'),
        ('orders', '0005_auto_20200204_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='product',
            new_name='inquired_product',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sold_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='shop.Product'),
        ),
    ]
