# Generated by Django 2.1.2 on 2018-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
