# Generated by Django 2.1.2 on 2018-11-11 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='serial_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
