# Generated by Django 2.1.4 on 2018-12-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='comments',
            field=models.TextField(blank=True, help_text='Дополнительные комментарии, что в комплекте продали и т.д.', null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(help_text='Выберите клиента', on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='laptop',
            field=models.ForeignKey(help_text='Выберите ноутбук', on_delete=django.db.models.deletion.CASCADE, to='laptop.Laptop'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за которую продали', max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='profit',
            field=models.DecimalField(decimal_places=2, help_text='Введите прибыль', max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(help_text='Количество'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='serial_number',
            field=models.CharField(help_text='Введите серийный номер', max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='warehouse',
            field=models.ForeignKey(help_text='Выберите магазин/склад', on_delete=django.db.models.deletion.CASCADE, to='warehouses.Warehouse'),
        ),
    ]
