# Generated by Django 2.1.5 on 2019-01-20 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
        ('laptop', '0007_laptop_old_price'),
        ('sales', '0008_auto_20181220_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Количество')),
                ('reason', models.TextField(help_text='Причина возврата')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('laptop', models.ForeignKey(help_text='Выберите ноутбук', on_delete=django.db.models.deletion.CASCADE, to='laptop.Laptop')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Выберите магазин/склад', on_delete=django.db.models.deletion.CASCADE, to='warehouses.Warehouse')),
            ],
            options={
                'verbose_name': 'Customer Return',
                'verbose_name_plural': 'Customer Returns',
            },
        ),
    ]
