# Generated by Django 2.2.4 on 2019-12-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='profit',
        ),
    ]
