# Generated by Django 2.2.4 on 2019-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Во множественном числе. К примеру: УльтрабукИ, трансформеры и т.д.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('name_singular', models.CharField(help_text='В единственном числе. К примеру: Ультрабук, трансформер и т.д.', max_length=200)),
                ('short_description', models.TextField()),
                ('logo', models.ImageField(default='default.png', upload_to='category/thumbs')),
            ],
            options={
                'verbose_name': 'Laptop Type',
            },
        ),
    ]
