# Generated by Django 2.2.4 on 2019-09-24 05:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0002_auto_20190406_1529'),
        ('brand', '0005_brand_active'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(default=1, help_text='Отсканируйте баркод', max_length=12)),
                ('name', models.CharField(help_text='К примеру: XPS 13', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('model', models.CharField(blank=True, help_text='К примеру: 1470 80XA', max_length=255, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('old_price', models.IntegerField(default=0, help_text='Старая цена. Оставьте 0 если не идет акция')),
                ('price', models.IntegerField(help_text='Введите сумму в USD')),
                ('viewed', models.IntegerField(blank=True, default=0, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='laptop_thumbnails')),
                ('awaiting', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='brand.Brand')),
                ('perks', models.ManyToManyField(blank=True, help_text='Выберите все нужные опции нажатием кнопки CTRL', to='perks.Perks')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_images/%Y-%m-%d/')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product')),
            ],
        ),
    ]
