# Generated by Django 2.2.4 on 2019-09-13 10:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190913_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='К примеру: Asus, Acer, HP и т.д.', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('logo', models.ImageField(upload_to='brands')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(help_text='Отсканируйте баркод', max_length=12)),
                ('name', models.CharField(help_text='К примеру: XPS 13', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('model', models.CharField(help_text='К примеру: 1470 80XA', max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('old_price', models.IntegerField(default=0, help_text='Старая цена. Оставьте 0 если не идет акция')),
                ('price', models.IntegerField(help_text='Введите сумму в USD')),
                ('viewed', models.IntegerField(blank=True, default=0, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails')),
                ('awaiting', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='products.Brand')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
