# Generated by Django 2.2.4 on 2019-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(help_text='Отсканируйте баркод', max_length=12, unique=True),
        ),
    ]
