# Generated by Django 2.2.4 on 2019-09-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='perks',
            field=models.ManyToManyField(blank=True, help_text='Выберите все нужные опции нажатием кнопки CTRL', null=True, to='products.Perks'),
        ),
    ]
