# Generated by Django 2.2.4 on 2020-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190925_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='perks',
            field=models.ManyToManyField(help_text='Выберите все нужные опции нажатием кнопки CTRL', to='products.Perks'),
        ),
    ]
